[workspace]
members = [
    "common/translations",
    "frontend/frontend_client", "frontend/admin_client", "frontend/yew_components",
    "backend/api_server", "backend/auth_service", "backend/subscription_service", "backend/utils"
]

