[package]
name = "components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { workspace = true, features = ["macros"] }
sycamore = "0.9.0-beta.2"
