application:
  port: 8080
  host: localhost
  key: "VdI8w9UnTdTetW2VvVWZtzLKrvxLWxc9ciLuBxDdB5Pc+9sSLnTW7eu21KK7Ht0pbErmtyo59XG/2XPJinSIZg=="
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "amrit_cms"
email:
  mode: Terminal
  sender: cms@amritghimire.com
frontend:
  assets: "frontend/client/dist"