application:
  port: 8080
  host: localhost
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "amrit_cms"
email:
  mode: Terminal
  sender: cms@amritghimire.com