[package]
name = "api_server"
edition = "2021"
version = "0.1.0"

[dependencies]
axum = "0.6.4"
log = "0.4.17"
once_cell = "1.17.1"
tracing-log = "0.1.3"

[dependencies.hyper]
version = "0.14.24"
features = ["full"]
optional = false

[dependencies.subscription_service]
path = "../subscription_service"
features = []
optional = false

[dependencies.tokio]
version = "1.25.0"
features = ["macros", "rt-multi-thread"]
optional = false

[dependencies.tower]
version = "0.4.13"
features = ["tracing", "tokio"]
optional = false

[dependencies.tower-http]
version = "0.3.5"
features = ["request-id", "trace"]
optional = false
default-features = false

[dependencies.tracing]
version = "0.1.37"
features = ["log"]
optional = false

[dependencies.tracing-subscriber]
version = "0.3.16"
features = ["env-filter", "registry", "tracing-log"]
optional = false

[dependencies.utils]
path = "../utils"
features = []
optional = false

[dependencies.uuid]
version = "1.3.0"
features = ["v4"]
optional = false
[dev-dependencies.tower]
version = "0.4.13"
features = ["util"]
optional = false

[lib]
path = "src/lib.rs"
plugin = false
proc-macro = false
required-features = []

[[bin]]
path = "src/main.rs"
name = "api_server"
plugin = false
proc-macro = false
required-features = []
